{% set name = "ai2-olmo-core" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ai2_olmo_core-{{ version }}.tar.gz
  sha256: 68c46c83222ddf5c0488899a4cce31f46d7b1a8416d6fb11362e409d75e61fe0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy<2
    - pytorch >=2.4,<2.6
    - safetensors
    - cached_path
    - requests
    - rich
    - omegaconf
    - importlib-resources
    - ai2-olmo-eval 0.2.0

test:
  imports:
    - olmo_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/allenai/OLMo-core
  summary: Core training module for the Open Language Model (OLMo)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
