{% set name = "ai2-olmo-core" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ai2_olmo_core-{{ version }}.tar.gz
  sha256: cac433ff0ae91d86c9d7ae20044d0d95219e94a3b1ebcda98477b1e94eeec8d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy
    - pytorch >=2.4,<2.5
    - safetensors
    - cached_path
    - requests
    - rich
    - omegaconf
    - importlib-resources

test:
  imports:
    - olmo_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/allenai/OLMo-core
  summary: Core training module for the Open Language Model (OLMo)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
