{% set name = "ai2-olmo-core" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ai2_olmo_core-{{ version }}.tar.gz
  sha256: 4dcb930ebf0f47447c6b1018c27e60f979f296d3bded4a1c6bde8ec541dadcf1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy <2
    - pytorch >=2.4,<2.6
    - safetensors
    - cached_path
    - requests
    - rich
    - omegaconf
    - importlib-resources
    - ai2-olmo-eval 0.2.0

test:
  imports:
    - olmo_core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/allenai/OLMo-core
  summary: Core training module for the Open Language Model (OLMo)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
