{% set name = "ai2-olmo-core" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ai2_olmo_core-{{ version }}.tar.gz
  sha256: d1c271c88cd82918e3419f610aee36ec7c2e3667930ab155d8912a4cf75503cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy <2
    - pytorch >=2.4,<2.6
    - safetensors
    - cached_path
    - requests
    - rich
    - omegaconf
    - importlib-resources

test:
  imports:
    - olmo_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/allenai/OLMo-core
  summary: Core training module for the Open Language Model (OLMo)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
