{% set name = "ai2-olmo-core" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ai2_olmo_core-{{ version }}.tar.gz
  sha256: 25f48abeedb3befddfe5c711138b094c151801f0b8fcde42c57677ddf932b6e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - bettermap
    - python >={{ python_min }}
    - numpy
    - pytorch >=2.6.0
    - cached_path >=1.7.2
    - requests
    - packaging
    - rich
    - omegaconf
    - safetensors
    - importlib_resources
    - ai2-olmo-eval ==0.7.1

test:
  imports:
    - olmo_core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/allenai/OLMo-core
  summary: Core training module for the Open Language Model (OLMo)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
