{% set name = "ai2-olmo-core" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ai2_olmo_core-{{ version }}.tar.gz
  sha256: 7bb6327de6a7646d2cd0533aa454491b5acc5d577e416987755eb3e737632960

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy
    - pytorch >=2.1
    - safetensors
    - pydantic >=2.0,<3.0
    - cached_path
    - requests
    - packaging

test:
  imports:
    - olmo_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/allenai/OLMo-core
  summary: Core training module for the Open Language Model (OLMo)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
